// content/freebies.js

// Kit form IDs — one form per freebie; the form's automation emails the PDF.
// release-replay-repair-return: Kit form doesn't exist yet — created in Task 9.
// Until its real ID is pasted in, the subscribe API rejects that slug (by design;
// never silently subscribe someone to the wrong guide).
// Community size shown under every freebie signup form. Update here as it grows.
const COMMUNITY_SIZE = '350K';

export const FREEBIES = {
  '4s-flowchart': {
    slug: '4s-flowchart',
    kitFormId: '9666050', // Kit form "Freebie: 4S Flowchart"
    pdfUrl: '/downloads/4s-flowchart-mobile.pdf',
    title: 'The 4S Flowchart',
    heroHeadline: 'Feelings aren’t facts. They’re information.',
    heroHeadlineItalic: 'They’re information.',
    heroSubhead: 'Your middle schooler’s brain is learning right now how emotion becomes action — and you’re the one they’re learning it from. The 4S Guide is a four-move teaching sequence for helping them make that jump, without arguing them out of the feeling or fixing it for them. Eight pages. Free.',
    microCopy: `Free. Part of my ${COMMUNITY_SIZE} community and counting.`,
    microCopyBold: COMMUNITY_SIZE,
    painPoints: [
      '“Every answer is a groan, an eye-roll, or ‘broooo.’”',
      '“I’m stuck between snapping at them and just handing over the iPad.”',
      '“Every feeling turns into a fight — or a lecture I didn’t mean to give.”',
      '“‘You’re fine’ keeps falling out of my mouth — and I hate it.”',
    ],
    painPointsCloser: '…then this guide was written for you.',
    painPointsCloserItalic: 'you',
    outcomesHeading: 'What changes at your kitchen table.',
    outcomesHeadingItalic: null,
    outcomes: [
      { title: 'Useful questions, real answers', description: 'Your kid starts telling you what’s actually going on, instead of “fine” and a shrug.' },
      { title: 'Talking about emotions gets less emotional', description: 'Big feelings stop spiralling into a fight — or a lecture you didn’t mean to give.' },
      { title: 'A kid who can name what they feel', description: 'They trade “lame” and “whatever” for words that actually move the moment forward.' },
      { title: 'A frame that hands them responsibility for their feelings', description: 'You walk into the hard moments knowing what to say — and when to step back.' },
    ],
    seanHeading: 'I ran a room of thirteen-year-olds for fourteen years.',
    seanHeadingItalic: 'thirteen-year-olds',
    seanBio: 'I taught middle-school English for fourteen years before I had three boys of my own. This guide is the same move I used to turn a roomful of thirteen-year-old groans into actual work — rewritten for the kitchen table.',
    modalEyebrow: 'The 4S Flowchart · free',
    coverTitle: 'The 4S Flowchart',
    coverTitleItalic: 'Flowchart',
    coverDescriptor: 'Turning middle-school emotions into action, out loud, in real time.',
    pageCount: '8 pages',
    metaTitle: 'The 4S Flowchart — Free Guide for Parents of Middle Schoolers',
    metaDescription: 'A free 8-page guide for parents of middle schoolers: the four-move sequence that turns groans and eye-rolls into real conversation. Get it tonight.',
  },

  'five-minute-meeting': {
    slug: 'five-minute-meeting',
    kitFormId: '9672214', // Kit form "Freebie: 5 Minute Meeting"
    pdfUrl: '/downloads/five-minute-meeting.pdf',
    readUrl: '/freebies/five-minute-meeting/read/', // shown in the "You're in" popup
    title: 'The Five-Minute Meeting',
    heroHeadline: 'The three-question meeting teachers use to build executive function.',
    heroHeadlineItalic: 'executive function.',
    heroSubhead: 'Middle schoolers don’t lack organization; they lack the working-memory scaffold to hold a plan without you. The Five Minute Meeting walks you through the sit-down that helps your kid see their responsibilities, sequence it, and own it — in less time than it takes to argue about homework. Fourteen pages. Free.',
    microCopy: `Free. Part of my ${COMMUNITY_SIZE} community and counting.`,
    microCopyBold: COMMUNITY_SIZE,
    painPoints: [
      '“I trip over their shoes on the way to nag about the homework — again.”',
      '“Every afternoon, I manage their whole to-do list.”',
      '“If it wasn’t for me, nothing would get done.”',
      '“I can’t be everyone’s executive function.”',
    ],
    painPointsCloser: '…then this guide was written for you.',
    painPointsCloserItalic: 'you',
    outcomesHeading: 'What changes by this afternoon.',
    outcomesHeadingItalic: 'this afternoon',
    outcomes: [
      { title: 'A kid who runs their own afternoon', description: 'They plan the homework, the priorities, and the timing — without you hovering over every step.' },
      { title: 'They own the homework, not you', description: 'Five minutes of the right questions, replaces an hour of nagging at the kitchen table.' },
      { title: 'Planning muscles that actually grow executive functions', description: 'They build the skills that support greater autonomy.' },
      { title: 'Calmer evenings for everyone', description: 'Fewer 9pm meltdowns, fewer reminders, more room to just be their parent.' },
    ],
    seanHeading: 'Fourteen years in room 201. Three sons at home.',
    seanHeadingItalic: 'room 201',
    seanBio: 'I taught middle-school English for fourteen years before I had three boys of my own. This guide is the same coaching move I used at a student’s desk — shrunk to fit a car ride and an afternoon.',
    modalEyebrow: 'The five-minute meeting · free',
    coverTitle: 'The five-minute meeting',
    coverTitleItalic: 'meeting',
    coverDescriptor: 'Three questions. Five minutes. One calmer afternoon.',
    pageCount: '14 pages',
    metaTitle: 'The Five-Minute Meeting — Free Guide for Parents of Middle Schoolers',
    metaDescription: 'A free 14-page guide: the five-minute conversation that builds executive function and hands your middle schooler\'s afternoon back to them.',
  },

  'release-replay-repair-return': {
    slug: 'release-replay-repair-return',
    kitFormId: '9672219', // Kit form "Freebie: Release, Replay, Repair, Return"
    pdfUrl: '/downloads/release-replay-repair-return.pdf',
    title: 'Release, Replay, Repair, Return',
    heroHeadline: 'Relationships aren’t defined by the fights. It’s built during the repair.',
    heroHeadlineItalic: 'repair',
    heroSubhead: 'Most blowups end the same way — you both move on, nothing repaired. This free, 10-page guide is the four-step conversation that turns the fight into the thing that brings you closer.',
    microCopy: `Free. Part of my ${COMMUNITY_SIZE} community and counting.`,
    microCopyBold: COMMUNITY_SIZE,
    painPoints: [
      '“We both say things we regret, then just… move on.”',
      '“I apologize, they shrug, but nothing actually changes.”',
      '“It’s the same blowup, on a loop.”',
      '“The least they could do is apologize.”',
    ],
    painPointsCloser: '…then this guide was written for you.',
    painPointsCloserItalic: 'you',
    outcomesHeading: 'What changes after the next fight.',
    outcomesHeadingItalic: 'next fight',
    outcomes: [
      { title: 'A way back after the blowup', description: 'You know exactly what to do in the ten minutes after a fight, instead of just moving on.' },
      { title: 'Fights that make you closer', description: 'The rupture becomes the moment your kid learns you always come back.' },
      { title: 'An end to the same fight on a loop', description: 'You solve the problem underneath instead of re-running the same argument.' },
      { title: 'A kid who learns to repair', description: 'They watch you own your part first — and start owning theirs.' },
    ],
    seanHeading: 'Fourteen years in room 201. Three sons at home.',
    seanHeadingItalic: 'room 201',
    seanBio: 'I taught middle school for fourteen years before I had three boys of my own. This guide is the loop I ran after every blowup — with a room of thirty, and now with three. Built on the research, and a lot of practice.',
    modalEyebrow: 'The repair guide · free',
    coverTitle: 'Release, replay, repair, return',
    coverTitleItalic: 'repair, return',
    coverDescriptor: 'The four-step conversation that repairs a rupture.',
    pageCount: '10 pages',
    metaTitle: 'Release, Replay, Repair, Return — Free Guide for Parents of Middle Schoolers',
    metaDescription: 'A free 10-page guide: the four-step conversation that turns a blowup with your middle schooler into something that actually brings you closer.',
  },

  'six-middle-skills': {
    slug: 'six-middle-skills',
    kitFormId: '9544138', // was 'field-guide' in the old (never-deployed) subscribe route
    pdfUrl: '/downloads/six-middle-skills-field-guide.pdf',
    title: 'The Six Middle Skills',
    heroHeadline: 'The skills that turn a kid into an adult.',
    heroHeadlineItalic: 'adult',
    heroSubhead: 'What looks like attitude at twelve is almost always a skill still loading. This free, 8-page field guide is a new lens for the slammed doors and one-word answers — and what each is quietly building toward.',
    microCopy: `Free. Part of my ${COMMUNITY_SIZE} community and counting.`,
    microCopyBold: COMMUNITY_SIZE,
    painPoints: [
      '“Homework turns into a nightly battle.”',
      '“The door slams and I’m not sure what I did.”',
      '“Same fight about the phone, every single day.”',
      '“They’ve just… checked out, and I can’t reach them.”',
    ],
    painPointsCloser: '…then this field guide was written for you.',
    painPointsCloserItalic: 'you',
    outcomesHeading: 'What changes when you see it differently.',
    outcomesHeadingItalic: 'see it differently',
    outcomes: [
      { title: 'A new way to read your kid', description: 'You start seeing a skill still loading instead of an attitude that needs correcting.' },
      { title: 'The end of “what’s wrong with my kid”', description: 'Defiance, laziness, and drama turn into signals you can actually work with.' },
      { title: 'Less reacting, more noticing', description: 'You catch what’s developing under the behavior before it becomes a fight.' },
      { title: 'A calmer, closer house', description: 'When you meet the skill instead of the symptom, the whole home settles.' },
    ],
    seanHeading: 'Fourteen years in room 201. Three sons at home.',
    seanHeadingItalic: 'room 201',
    seanBio: 'I taught middle-school English for fourteen years before I had three boys of my own. This guide is the lens I used to tell the difference between a kid being difficult and a kid building something — rewritten for the kitchen table.',
    modalEyebrow: 'The six middle skills · free',
    coverTitle: 'The six middle skills',
    coverTitleItalic: 'middle skills',
    coverDescriptor: 'A lens for what your middle schooler is quietly building.',
    pageCount: '8 pages',
    metaTitle: 'The Six Middle Skills — Free Field Guide for Parents of Middle Schoolers',
    metaDescription: 'A free 8-page field guide: the six skills your middle schooler is still building, what each one looks like, and the move that\'s yours to make.',
  },
  'emotional-literacy': {
    slug: 'emotional-literacy',
    kitFormId: '9852097', // Kit form "Freebie: Emotional Literacy for Kids"
    pdfUrl: '/downloads/emotional-literacy-for-kids.pdf',
    title: 'Emotional Literacy for Kids',
    heroEyebrow: 'Free guide · For middle schoolers', // this guide is for the kid, not the parent
    heroHeadline: 'Nobody controls everything they feel. Everyone controls what they do next.',
    heroHeadlineItalic: 'what they do next.',
    heroSubhead: 'Adolescence puts the emotional part of your kid’s brain into overdrive before the deciding part has caught up — which is why the crash-out comes out of nowhere. This free, 6-page guide explains that to your nine-to-thirteen-year-old in their own language: the Lizard and the Wizard, the five feeling chemicals, and the questions that turn a reaction into a choice. Written for them to read, not you.',
    microCopy: `Free. Part of my ${COMMUNITY_SIZE} community and counting.`,
    microCopyBold: COMMUNITY_SIZE,
    painPoints: [
      '“They crash out over nothing, and then can’t tell me why.”',
      '“Every feeling comes out as anger, or a slammed door.”',
      '“‘Just calm down’ keeps falling out of my mouth — and it makes it worse.”',
      '“I can explain it, but they will not hear it from me.”',
    ],
    painPointsCloser: '…then this guide was written for your kid.',
    painPointsCloserItalic: 'your kid.',
    outcomesHeading: 'What changes once they read it themselves.',
    outcomesHeadingItalic: 'themselves',
    outcomes: [
      { title: 'They stop thinking something is wrong with them', description: 'The flood of feeling gets a real explanation — brain chemistry on a schedule, not a character flaw.' },
      { title: 'A name for the crash-out', description: 'The Lizard and the Wizard gives them words for losing it, and a reason to believe the Wizard wins more often over time.' },
      { title: 'Five questions to run in their own head', description: 'What am I feeling, where did it come from, who needs to know — a script that fits between the feeling and the reaction.' },
      { title: 'It doesn’t have to come from you', description: 'The explanation lands without becoming one more lecture from a parent.' },
    ],
    seanHeading: 'I gave this talk to thirteen-year-olds for fourteen years.',
    seanHeadingItalic: 'thirteen-year-olds',
    seanBio: 'I taught middle-school English for fourteen years before I had three boys of my own. This is the conversation I had at a desk in room 201 every time a kid melted down — written straight to your kid, in their language, not mine.',
    modalEyebrow: 'Emotional literacy for kids · free',
    coverTitle: 'Emotional literacy for kids',
    coverTitleItalic: 'for kids',
    coverDescriptor: 'The puberty brain, explained straight to your nine-to-thirteen-year-old.',
    pageCount: '6 pages',
    metaTitle: 'Emotional Literacy for Kids — A Free Guide to Hand Your Middle Schooler',
    metaDescription: 'A free 6-page guide written for 9–13 year olds: why puberty makes feelings feel out of control, the five feeling chemicals, and the questions that turn a crash-out into a choice.',
  },
  'capable': {
    slug: 'capable',
    kitFormId: '9926763', // Kit form "Freebie: Capable"
    pdfUrl: '/downloads/capable.pdf',
    title: 'Capable',
    heroEyebrow: 'Free essay · For parents of middle schoolers',
    heroHeadline: 'My kid is capable, so why am I still doing everything?',
    heroHeadlineItalic: 'doing everything?',
    heroSubhead: 'Your kid can memorize every player on an NBA roster and negotiate bedtime for 30 minutes, and still can’t get out the door without you. This free, 6-page essay names the problem hiding inside this phase, and one thing to look at differently this week.',
    microCopy: `Free. Part of my ${COMMUNITY_SIZE} community and counting.`,
    microCopyBold: COMMUNITY_SIZE,
    painPoints: [
      '“I’ve told you a thousand times.”',
      '“You need to start handling some of this on your own.”',
      '“I don’t ask you for much!”',
      '“Have you seen what happens when I stop reminding you?”',
    ],
    painPointsCloser: '…then this essay was written for you.',
    painPointsCloserItalic: 'you',
    outcomesHeading: 'What changes when you see the gap.',
    outcomesHeadingItalic: 'see the gap',
    outcomes: [
      { title: 'Frustration becomes a problem you can solve', description: 'You stop reading it as a kid who doesn’t care, and start seeing skills that are still developing.' },
      { title: 'A clear picture of what you’re carrying', description: 'One week of noticing shows you everything you do to make one task happen: the reminding, the checking, the clock-watching.' },
      { title: 'Why the lecture never lands', description: 'Your kid already knows. The gap is in the doing, and the doing is a skill you can teach.' },
      { title: 'A way forward that isn’t yelling or walking away', description: 'Not doing everything for them, and not backing off and hoping. The space in between is where family life gets easier.' },
    ],
    seanHeading: 'Fourteen years in room 201. Three sons at home.',
    seanHeadingItalic: 'room 201',
    seanBio: 'I taught middle-school English for fourteen years before I had three boys of my own. When a student couldn’t write an essay, I never said “you’re in seventh grade, you know how.” I found where the process fell apart and taught that part. This essay points that same teacher brain at the kitchen table.',
    modalEyebrow: 'Capable · free essay',
    coverTitle: 'My kid is capable',
    coverTitleItalic: 'capable',
    coverDescriptor: 'So why am I still doing everything?',
    pageCount: '6 pages',
    metaTitle: 'My Kid Is Capable, So Why Am I Still Doing Everything? (Free Essay)',
    metaDescription: 'A free 6-page essay for parents of middle schoolers: why capable kids still depend on you for everything, and one thing to look at differently this week.',
  },
  'collapsing-cruelty': {
    slug: 'collapsing-cruelty',
    kitFormId: '9934137', // Kit form "Freebie: Collapsing Cruelty"
    pdfUrl: null, // no PDF on the site; the essay is read on the web
    readUrl: '/freebies/collapsing-cruelty/read/', // shown in the "You're in" popup
    title: 'Collapsing Cruelty',
    heroEyebrow: 'Free essay · For parents of middle schoolers',
    heroHeadline: 'Cruelty continues when it’s rewarded. It collapses when it’s interrupted.',
    heroHeadlineItalic: 'It collapses when it’s interrupted.',
    heroSubhead: 'Sibling cruelty happens right in front of us: in the kitchen, in the car, in the hallway. This free essay explains why it keeps paying off for the kid doing it, and how to interrupt, separate and follow through without escalating. Scripts included.',
    microCopy: `Free. Part of my ${COMMUNITY_SIZE} community and counting.`,
    microCopyBold: COMMUNITY_SIZE,
    painPoints: [
      '“I don’t care who started it.”',
      '“Why can’t you just be nice to your brother?”',
      '“Can you two please leave each other alone?”',
      '“Just ignore her.”',
    ],
    painPointsCloser: '…then this essay was written for you.',
    painPointsCloserItalic: 'you',
    outcomesHeading: 'What changes when cruelty stops paying off.',
    outcomesHeadingItalic: 'stops paying off',
    outcomes: [
      { title: 'You see what the cruelty is getting them', description: 'Laughter, attention, control. Once you see the reward, you can take it away without taking it personally.' },
      { title: 'A clear move for the moment it happens', description: 'Brief, firm, no debate. Interrupt, separate, and go to the child who was hurt first.' },
      { title: 'Words for the pushback', description: '“You always take their side.” “I said I was sorry!” The essay gives you what to say back, calmly.' },
      { title: 'Follow up that builds self-control', description: 'Seven questions for once everyone has cooled off, so your interruption slowly becomes their own.' },
    ],
    seanHeading: 'Fourteen years in room 201. Three sons at home.',
    seanHeadingItalic: 'room 201',
    seanBio: 'I taught middle-school English for fourteen years before I had three boys of my own. The teachers who rarely saw bullying weren’t lucky. They interrupted it early and followed through every time. This essay brings that same move to the kitchen table.',
    modalEyebrow: 'Collapsing Cruelty · free essay',
    coverTitle: 'Collapsing cruelty',
    coverTitleItalic: 'cruelty',
    coverDescriptor: 'How parents can disrupt the function inside sibling cruelty and conflict.',
    pageCount: '12 min read',
    metaTitle: 'Collapsing Cruelty: How to Stop Sibling Cruelty (Free Essay for Parents)',
    metaDescription: 'A free essay for parents of middle schoolers: why sibling cruelty keeps paying off, and how to interrupt, separate and follow through without escalating. Scripts included.',
  },
};

export function getFreebie(slug) {
  return FREEBIES[slug] || null;
}

export function getAllFreebies() {
  return Object.values(FREEBIES);
}